### ISSUE TITLE
Antenna is connected to PABOOST

### ISSUE THREAD

**Issue by rogerdahl** [USIWP1Module/USI_I-NUCLEO-LRWAN1#2]
Hi, I think you forgot to mention that the driver must be configured to use the PA_BOOST output on the SX1272. I modified `sx1272mb2das.c` as follows:

```
uint8_t SX1272GetPaSelect(uint32_t channel)
{
  return RF_PACONFIG_PASELECT_PABOOST; // RF_PACONFIG_PASELECT_RFO
}
```

And set `TX_OUTPUT_POWER` to 20 (dBm) in the call to `SetTxConfig()`.

**Comment by USI-ShellyWu** [comment]
Already updated readme.

(5) since SM42 uses PA_BOOST for the RF TX, please change the RFLR_PACONFIG_PASELECT_RFO value from 0x00 to 0x80 in the header files below: 'en.i-cube_lrwan\STM32CubeExpansion_LRWAN_V1.1.4\Drivers\BSP\Components\sx1272\sx1272Regs-Fsk.h' 'en.i-cube_lrwan\STM32CubeExpansion_LRWAN_V1.1.4\Drivers\BSP\Components\sx1272\sx1272Regs-Lora.h'
